name: Create Blender Plugin Zip
on:
  push:
    tags:
      - '*-alpha'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'TRACER-Blender-4.2LTS.zip'
        path: 'Blender'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        name: 'BlenderAddOn-Release'
        draft: True
        artifacts: 'TRACER-Blender-4.2LTS.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
