name: Create Blender Plugin Zip
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        path: 'Blender'
        exclusions: '*.git* /*node_modules/* .editorconfig'
